config {
    name: "moja_nowa_tabela",
    type: "table",
    description: "moja pierwsza nowa tabela",
    tags: ["tabela", "moja", "nowa"],
    schema: "bqml",
    columns: {
        unique_id: "Unikalne id usera",
        status: "Status usera",
        wiek: "Wiek usera",
        zarobki: "Zarobki",
        uro: "Urodziny"
    },
    bigquery: {
        partitionBy: "uro"
    }
}

SELECT
  1 AS unique_id,
  2 AS status,
  3 AS wiek