config {
    name: "moja_nowa_tabela_2",
    type: "table",
    description: "moja pierwsza nowa tabela",
    tags: ["tabela", "moja", "nowa"],
    columns: {
        unique_id: "Unikalne id usera",
        status: "Status usera",
        wiek: "Wiek usera",
        zarobki: "Zarobki",
        uro: "Urodziny"
    }
}

CREATE TABLE
  ml-pl-test.bqml.moja_nowa_tabela_2 AS
SELECT
  1 AS unique_id
